# Crawler configs are grouped by city and cities are sorted alphabetically.

crawlers:
  ##########
  # Bologna
  ##########
  - name: LocomotivClub
    type: concert
    city: Bologna
    url: "https://www.locomotivclub.it/eventtype/calendario/"
    event: ".qt-item-event"
    fields:
      - name: "title"
        type: "text"
        selector: ".qt-text-shadow"
      - name: "comment"
        type: "text"
        selector: ".qt-the-content div"
        on_subpage: true
      - name: "url"
        type: "url"
        selector: ".qt-text-shadow"
      - name: "date"
        type: "date"
        on_subpage: true
        components:
          - part: "day_month_year"
            selector: ".qt-eventtable tr td"
            # layout: " Data: 2 Febbraio 2022"
            layout: " Data: 2 January 2006"
            regex_extract:
              exp: "\\sData:.*"
          - part: "time"
            selector: ".qt-eventtable tr td"
            node_index: 2
            # layout: " Inizio concerto: 9:30 pm"
            layout: " Inizio concerto: 3:04 pm"
            regex_extract:
              exp: " Inizio concerto: .*"
        location: "Europe/Berlin"
        language: "it_IT"
    filters:
      - field: "title"
        regex_ignore: ".*CANCELED.*"
      - field: "title"
        regex_ignore: "ANNULLATO!.*"
      - field: "title"
        regex_ignore: ".*Postponed.*"
    paginator:
      selector: ".pagination .qt-btn-primary"
      node_index: -1
      max_pages: 4