crawlers:
  - name: Helsinki
    type: concert
    url: https://www.helsinkiklub.ch
    event: ".event .header"
    fields:
      title: # only the first option that results in an non-empty title is taken into account.
        - ".agenda .top"
        - ".agenda .support"
      comment:
        - ".agenda .top .addition"
        - ".agenda .support .addition"
      date:
        day:
          loc: ".day"
          layout: "2"
        month:
          loc: ".month"
          layout: "January" # has to be in English
        location: "Europe/Berlin"
        language: "de_DE"
  #     day:
  #     month:

  #   date_format: ""

  - name: Mehrspur
    type: concert
    url: "https://www.mehrspur.ch/veranstaltungen"
    event: ".post-holder"
    fields:
      title:
        - ".block_under_title a"
      url:
        loc: ".block_under_title a"
      comment:
        - ".event-excerpt-fluid"

  - name: Umbo
    type: concert
    url: "https://www.umbo.wtf"
    event: ".w-dyn-item"
    fields:
      title:
        - ".text-block-21"
      url:
        loc: ".w-inline-block"
        relative: true
