# Crawler configs are grouped by city and cities are sorted alphabetically.

crawlers:
  ##########
  # Bologna
  ##########
  - name: LocomotivClub
    type: concert
    city: Bologna
    url: "https://www.locomotivclub.it/eventtype/calendario/"
    event: ".qt-item-event"
    fields:
      - name: "title"
        type: "text"
        location:
          selector: ".qt-text-shadow"
      - name: "comment"
        type: "text"
        location:
          selector: ".qt-the-content div"
        can_be_empty: true
        on_subpage: "url"
      - name: "url"
        type: "url"
        location:
          selector: ".qt-text-shadow"
      - name: "date"
        type: "date"
        on_subpage: "url"
        components:
          - covers:
              day: true
              month: true
              year: true
            location:
              selector: ".qt-eventtable tr td"
              regex_extract:
                exp: "\\sData:.*"
              child_index: -1
            # layout: " Data: 2 Febbraio 2022"
            layout: " Data: 2 January 2006"
          - covers:
              time: true
            location:
              selector: ".qt-eventtable tr td"
              node_index: 2
              regex_extract:
                exp: " Inizio concerto: .*"
              child_index: -1
            # layout: " Inizio concerto: 9:30 pm"
            layout: " Inizio concerto: 3:04 pm"
        date_location: "Europe/Berlin"
        date_language: "it_IT"
    filters:
      - field: "title"
        regex_ignore: ".*CANCELED.*"
      - field: "title"
        regex_ignore: "ANNULLATO!.*"
      - field: "title"
        regex_ignore: ".*Postponed.*"
    paginator:
      selector: ".pagination .qt-btn-primary"
      node_index: -1
      max_pages: 4