crawlers:
  - name: Helsinki
    type: concert
    url: https://www.helsinkiklub.ch
    event: ".event .header"
    fields:
      title: ".agenda .top"
      comment: ".agenda .top .addition"
      date:
        day: ".day"
        month: ".month"
        location: "Europe/Berlin"
        language: "DE"
  #     day:
  #     month:

  #   date_format: ""

  - name: Mehrspur
    type: concert
    url: "https://www.mehrspur.ch/veranstaltungen"
    event: ".post-holder"
    fields:
      title: ".block_under_title a"
      url: 
        loc: ".block_under_title a"
      comment: ".event-excerpt-fluid"

  - name: Umbo
    type: concert
    url: "https://www.umbo.wtf"
    event: ".w-dyn-item"
    fields:
      title: ".text-block-21"
      url:
        loc: ".w-inline-block"
        relative: true