crawlers:
  - name: Helsinki
    type: concert
    url: https://www.helsinkiklub.ch
    city: "Zurich"
    event: ".event .header"
    fields:
      title: # only the first option that results in a non-empty title is taken into account.
        - ".agenda .top"
        - ".agenda .support"
      comment: # only the first option that results in a non-empty comment is taken into account.
        - ".agenda .top .addition"
        - ".agenda .support .addition"
      date:
        day:
          loc: ".day"
          layout: "2"
        month:
          loc: ".month"
          layout: "January" # has to be in English
        location: "Europe/Berlin"
        language: "de_DE"

  - name: Mehrspur
    type: concert
    url: "https://www.mehrspur.ch/veranstaltungen"
    city: "Zurich"
    event: ".post-holder"
    fields:
      title:
        - ".block_under_title a"
      url:
        loc: ".block_under_title a"
      comment:
        - ".event-excerpt-fluid"
      date:
        day_month:
          loc: ".event-date"
          layout: "Mon 2.Jan."
        time:
          loc: ".event-time"
          layout: "15:04"
        location: "Europe/Berlin"
        language: "de_DE"

  - name: Umbo
    type: concert
    url: "https://www.umbo.wtf"
    city: "Zurich"
    event: ".w-dyn-item"
    fields:
      title:
        - ".text-block-21"
      comment:
        - ".text-block-28"
      url:
        loc: ".w-inline-block"
        relative: true
      date:
        day_month_year_time:
          loc: ".text-block-26"
          layout: "2.1.2006 15:04"
        location: "Europe/Berlin"

  - name: Sender
    type: concert
    url: "https://gds.fm/SENDER"
    city: "Zurich"
    event: ".event-list__item"
    fields:
      title:
        - ".event-preview__title"
      url:
        loc: "" # An empty string means that we look in the event node itself for an href
        relative: true
      date:
        day_month_year_time:
          loc: ".event-preview__date-long"
          layout: "January 02, 2006, 03:04 PM"
        location: "GMT"
        language: "en_US"

  - name: Unterfahrt
    type: concert
    url: "https://www.unterfahrt.de/programm.php"
    city: "Munich"
    event: ".b-events__el"
    fields:
      title: 
        - ".b-events__el-title"
      comment:
        - ".b-events__el-text"
      url:
        loc: ".o-btn-cta__link"
        relative: true
      date:
        day_month_year_time:
          loc: ".b-events__el-date"
          layout: "Mon•2•1•2006, 15••04"
        location: "Europe/Berlin"
        language: "de_DE"

