# Crawler configs are grouped by city and cities are sorted alphabetically.

crawlers:
  ##########
  # Bologna
  ##########
  - name: LocomotivClub
    type: concert
    city: Bologna
    url: "https://www.locomotivclub.it/eventtype/calendario/"
    event: ".qt-item-event"
    fields:
      title:
        selector: ".qt-text-shadow"
      comment:
        selector: ".qt-the-content div"
      url:
        selector: ".qt-text-shadow"
        on_subpage: ["comment", "date"]
      date:
        day_month_year:
          selector: ".qt-eventtable tr td"
          # layout: " Data: 2 Febbraio 2022"
          layout: " Data: 2 January 2006"
          regex_extract:
            exp: "\\sData:.*"
        time:
          selector: ".qt-eventtable tr td"
          node_index: 2
          # layout: " Inizio concerto: 9:30 pm"
          layout: " Inizio concerto: 3:04 pm"
          regex_extract:
            exp: " Inizio concerto: .*"
        location: "Europe/Berlin"
        language: "it_IT"
    filters:
      - field: "title"
        regex_ignore: ".*CANCELED.*"
      - field: "title"
        regex_ignore: "ANNULLATO!.*"
      - field: "title"
        regex_ignore: ".*Postponed.*"
    paginator:
      selector: ".pagination .qt-btn-primary"
      node_index: -1
      max_pages: 4

  ##########
  # Brussels
  ##########
  - name: Botanique
    type: concert
    city: Brussels
    url: "https://botanique.be/en/concerts"
    event: ".views-content .event-type-concert"
    fields:
      title:
        selector: ".node-type-event__title h2 a span"
      comment:
        selector: ".location-list li"
      url:
        selector: ".node-type-event__title h2 a"
        relative: true
      date:
        day:
          selector: ".node-date__day"
          layout: "02"
        month:
          selector: ".node-date__month"
          layout: "Jan"
        year:
          selector: ".node-date__year"
          layout: "2006"
        time:
          selector: ".node-type-event__timing"
          layout: "15:04"
          regex_extract:
            exp: "[0-9]{2}:[0-9]{2}"
        location: "Europe/Berlin"
        language: "en_US"
    paginator:
      selector: ".pager__item a"
      relative: true
    filters:
      - field: "title"
        regex_ignore: ".*POSTPONED.*"
      - field: "title"
        regex_ignore: ".*CANCELLED.*"

  ##########
  # Leuven
  ##########
  - name: HetDepot
    type: concert
    city: Leuven
    url: "https://www.hetdepot.be/programma"
    event: ".calendar-item"
    fields:
      title:
        selector: ".calendar-item__title"
      comment:
        selector: ".calendar-item__intro p"
      url:
        selector: ".calendar-item__inner a"
        relative: true
        on_subpage: ["date"]
      date:
        day_month_year_time:
          selector: ".concert__date time"
          layout: "Monday 2 Jan 2006 - 15:04"
        location: "Europe/Berlin"
        language: "nl_BE"
    paginator:
      selector: ".pager__item--next a"
      relative: true

  ##########
  # Munich
  ##########
  - name: Unterfahrt
    type: concert
    url: "https://www.unterfahrt.de/programm.php"
    city: "Munich"
    event: ".b-events__el"
    fields:
      title: 
        selector: ".b-events__el-title"
      comment:
        selector: ".b-events__el-text"
        max_length: 200
      url:
        selector: ".o-btn-hex__link"
        relative: true
      date:
        day_month_year:
          selector: ".b-events__el-date"
          layout: "Mon•2•1•2006"
          regex_extract: # In case the node contains more than just the desired string the substring can be determined with a regex
            exp: "[A-Za-z]{2}•[0-9]{1,2}•[0-9]{1,2}•[0-9]{4}"
            index: 0
        time:
          selector: ".b-events__el-date"
          layout: "15••04"
          regex_extract:
            exp: "[0-9]{2}••[0-9]{2}"
            index: -1
        location: "Europe/Berlin"
        language: "de_DE"

  - name: ImportExport
    type: concert
    url: "https://import-export.cc/"
    city: "Munich"
    event: ".events a"
    exclude_with_selector: 
      - ".old" # events that have a node with this class will be excluded from the results.
    fields:
      url:
        selector: ""
        on_subpage: ["date"]
      title:
        selector: ".io-title"
      date:
        day_month_year:
          selector: ".event .event-info .io-big"
          layout: "Mon. 2.1.06"
          node_index: 0
        time:
          selector: ".event .event-info .io-big"
          node_index: 3 # We need this in case there are multiple nodes that would be selected with the given loc
          layout: "Beginn: 15.04"
        location: "Europe/Berlin"
        language: de_DE
      
  - name: Milla
    type: concert
    city: Munich
    url: "https://www.milla-club.de/category/event/"
    event: ".preview-box-outline"
    fields:
      url:
        selector: ".post-title a"
      title:
        selector: ".post-title a"
      date:
        day:
          selector: ".post-date-day"
          layout: "02"
        month:
          selector: ".post-date-month"
          layout: "Jan"
        year:
          selector: ".post-date-year"
          layout: "2006"
        location: "Europe/Berlin"
        language: "de_DE"

  - name: Backstage
    type: concert
    city: Munich
    url: "https://backstage.info/veranstaltungen-2/alle-veranstaltungen"
    event: ".event"
    fields:
      title:
        selector: ".pos-title a"
      comment:
        selector: ".event h3"
      url:
        selector: ".pos-title a"
        relative: true
        on_subpage: ["comment", "date"]
      date:
        day_month_year:
          selector: ".pos-datum b"
          layout: "Monday, 2. January 2006"
        time:
          selector: ".pos-einlass"
          layout: "Beginn: 15:04"
          regex_extract:
            exp: "Beginn: [0-9]{1,2}:[0-9]{2}"
            index: 0
        location: "Europe/Berlin"
        language: "de_DE"
    filters:
      - field: "title"
        regex_ignore: "CORONA TESTZENTRUM.*"
    paginator:
      selector: ".pagination .next"
      relative: true
      max_pages: 2 # otherwise this crawler takes ages.

  - name: Strom
    type: concert
    city: Munich
    url: "https://strom-muc.de/"
    event: ".gdlr-event-item"
    exclude_with_selector:
      - ".cancelled-button"
      - ".coming-soon"
    fields:
      title:
        selector: ".event-title a"
      url:
        selector: ".event-title a"
        on_subpage: ["date"]
      date:
        day_month_year:
          selector: ".gdlr-info-date"
          layout: "02.01.2006"
          regex_extract:
            exp: "([0-9]{2}\\.){2}[0-9]{4}"
        time:
          selector: ".gdlr-info-time"
          layout: "15.04"
          regex_extract:
            exp: "[0-9]{2}(\\.|:)[0-9]{2}"
            index: -1
        location: "Europe/Berlin"

  - name: Muffatwerk
    type: concert
    city: Munich
    url: "https://www.muffatwerk.de/de/events/concert"
    event: ".row .event"
    fields:
      title:
        selector: ".hover-in .center span"
      url:
        selector: ".hover-in .right a"
        relative: true
      date:
        day_month:
          selector: ".hover-in .center"
          layout: "02.01. "
          regex_extract:
            exp: "([0-9]{2}\\.){2}\\s"
        year:
          selector: ".date"
          layout: "06	" # the whitespace in this string is a tab.
          regex_extract:
            exp: "[0-9]{2}\\s"
        time:
          selector: ".hover-in .center"
          layout: "15:04"
          regex_extract:
            exp: "[0-9]{2}:[0-9]{2}"
        location: "Europe/Berlin"

  ##########
  # Paris
  ##########
  - name: LaCigale
    type: concert
    url: "http://www.lacigale.fr/en/"
    city: "Paris"
    event: ".spectacle-infos"
    fields:
      title:
        selector: ".title .text-white"
      url:
        selector: ".mobile a"
        on_subpage: ["comment", "date"]
      comment:
        selector: ".c-m-7 .infos-wrapper .text-grey"
      date:
        day_month_year:
          selector: ".c-m-7 .date-wrapper .text-grey"
          layout: "02 January 2006"
        time:
          selector: ".c-m-6 .hour"
          layout: "15 H 04"
          regex_extract:
            exp: "[0-9]{2}\\sH\\s[0-9]{2}"
        location: "Europe/Paris"
        language: en_US

  ##########
  # Zurich
  ##########
  - name: Helsinki
    type: concert
    url: https://www.helsinkiklub.ch
    city: "Zurich"
    event: ".event .header"
    fields:
      title: 
        selector: ".agenda > .top,.support"
          # - ".agenda .top"
          # - ".agenda .support"
      comment: 
        selector: ".agenda > .top .addition,.support .addition"
          # - ".agenda .top .addition"
          # - ".agenda .support .addition"
      date:
        day:
          selector: ".day"
          layout: "2"
        month:
          selector: ".month"
          layout: "January" # has to be in English
        location: "Europe/Berlin"
        language: "de_DE"

  - name: Mehrspur
    type: concert
    url: "https://www.mehrspur.ch/veranstaltungen"
    city: "Zurich"
    event: ".post-holder"
    fields:
      title:
        selector: ".block_under_title a"
      comment:
        selector: ".event-excerpt-fluid"
      url:
        selector: ".block_under_title a"
      date:
        day_month:
          selector: ".event-date"
          layout: "Mon 2.Jan."
        time:
          selector: ".event-time"
          layout: "15:04"
        location: "Europe/Berlin"
        language: "de_DE"

  - name: Umbo
    type: concert
    url: "https://www.umbo.wtf"
    city: "Zurich"
    event: ".w-dyn-item"
    fields:
      title:
        selector: ".text-block-21"
      comment:
        selector: ".text-block-28"
      url:
        selector: ".w-inline-block"
        relative: true
      date:
        day_month_year_time:
          selector: ".text-block-26"
          layout: "2.1.2006 15:04"
        location: "Europe/Berlin"

  - name: Sender
    type: concert
    url: "https://gds.fm/SENDER"
    city: "Zurich"
    event: ".event-list__item"
    fields:
      title:
        selector: ".event-preview__title"
      comment:
        selector: ".event-detail__content div p"
        max_length: 200
      url:
        selector: "" # An empty string means that we look in the event node itself for an href
        relative: true
        on_subpage: ["comment"]
      date:
        day_month_year_time:
          selector: ".event-preview__date-long"
          layout: "January 02, 2006, 03:04 PM"
        location: "GMT"
        language: "en_US"

  - name: Moods
    type: concert
    url: "https://www.moods.club/en/?a=1"
    city: "Zurich"
    event: ".event"
    fields:
      url:
        selector: "a"
        relative: true
        on_subpage: ["comment", "date"]
      title:
        selector: "h2"
      comment:
        selector: ".left .content"
        max_length: 200
      date:
        day:
          selector: ".date .day"
          layout: "2"
        month:
          selector: ".date .month_name"
          layout: "Jan"
        time:
          selector: ".right .time"
          layout: "Start: 15:04"
          node_index: -1 # -1 means the last node
        location: "Europe/Berlin"
        language: "en_US"

  - name: ElLokal
    type: concert
    city: Zurich
    url: "http://www.ellokal.ch/?lang=de&details=9"
    event: "#maincontent > .commingupEventsList_0,.commingupEventsList_1"
    fields:
      title:
        selector: ".commingupEventsList_block5 a"
      comment:
        selector: ".concertStyleNew .concertDetails"
      url:
        selector: ".commingupEventsList_block5 a"
        relative: true
        on_subpage: ["comment"]
      date:
        day:
          selector: ".commingupEventsList_block2"
          layout: "02. "
        month:
          selector: ".commingupEventsList_block3"
          layout: "January"
        time:
          selector: ".commingupEventsList_block4"
          layout: "15Uhr04"
        location: "Europe/Berlin"
        language: "de_DE"
        
  - name: Mascotte
    type: concert
    city: Zurich
    url: "https://www.mascotte.ch/nu/events/event_list_type/2"
    event: ".nu-e-concert"
    fields:
      title: 
        selector: ".screen-only h2"
      comment:
        selector: ".nu-e-subt"
      url:
        selector: ".nu-e-link-share"
        attr: "data-a2a-url"
      date:
        day_month_year:
          selector: ".screen-only .nu-e-date"
          layout: "2.1.06"
          regex_extract:
            exp: "([0-9]{1,2}\\.){2}[0-9]{2}"
            index: 0
        time:
          selector: ".nu-e-time-age"
          layout: "15.04"
          regex_extract:
            exp: "[0-9]{2}\\.[0-9]{2}"
            index: 1 
        location: "Europe/Berlin"

  - name: Kaufleuten
    type: concert
    city: Zurich
    url: "https://kaufleuten.ch/events/kultur/konzerte/"
    event: ".event"
    fields:
      title:
        selector: "h3"
        regex_extract:
          exp: "[^•]*"
          index: 0
      comment:
        selector: ".subtitle strong"
      url:
        selector: ".event-link"
        on_subpage: ["date"]
      date:
        day_month_year:
          selector: ".event-meta time"
          layout: "Monday, 02.01.2006"
          regex_extract:
            exp: "[a-zA-Z]+,\\s([0-9]{2}\\.){2}[0-9]{4}"
            index: 0
        time:
          selector: ".event-meta .quick-facts li"
          layout: "15:04"
          node_index: 2 # if there are still multiple text nodes under this node the first one that results in a regex match, will be used
          regex_extract:
            exp: "[0-9]{2}:[0-9]{2}"
            index: 0
        location: "Europe/Berlin"
        language: "de_DE"

  - name: Tonhalle
    type: concert
    city: Zurich
    url: "https://www.tonhalle-orchester.ch/en/home-tz/konzerte/kalender/"
    event: ".js-calendarlist-list .data"
    fields:
      title:
        selector: ".event h3"
      comment:
        selector: ".member .member-name"
        node_index: 1
      url:
        selector: ".desktop-linkoverlay"
        relative: true
      date:
        day_month:
          selector: ".col-left .date"
          layout: "2. Jan"
          regex_extract:
            exp: "[0-9]{1,2}\\.\\s[a-zA-Z]{3}"
        time:
          selector: ".col-left .hour"
          layout: "15.04"
          regex_extract:
            exp: "[0-9]{1,2}\\.[0-9]{2}"
        location: "Europe/Berlin"
        language: "de_DE"
    paginator:
      selector: ".MarkupPagerNavNext a"
      relative: true

  - name: Heldenbar
    type: concert
    city: Zurich
    url: "https://www.heldenbar.ch/programm/"
    event: ".page-content .vsel-upcoming"
    fields:
      title:
        selector: ".vsel-meta-title a"
      comment:
        selector: ".vsel-info p"
      url:
        selector: ".vsel-meta-title a"
        on_subpage: ["date"]
      date:
        day_month_year:
          selector: ".vsel-meta-date span"
          layout: "2/01/2006"
          regex_extract:
            exp: "([0-9]{2}/){2}[0-9]{4}"
        time:
          selector: ".vsel-meta-time span"
          layout: "15:04"
          regex_extract:
            exp: "[0-9]{1,2}:[0-9]{2}"
        location: "Europe/Berlin"
        language: "de_DE"

  - name: Exil
    type: concert
    city: Zurich
    url: "https://exil.cl/programm"
    event: "#detail-main article"
    exclude_with_selector: 
      - ".wct_event"
    fields:
      title:
        selector: ".grid-event-title"
      comment:
        selector: ".hyphenate p"
        max_length: 200
      date:
        day_month_year_time:
          selector: ".grid-event-date"
          layout: "2006-01-02T15:04"
          attr: "datetime"
        location: "Europe/Berlin"
        language: "de_DE"
    filters:
      - field: "title"
        regex_ignore: ".*abgesagt.*"
      - field: "title"
        regex_ignore: "geschlossene Gesellschaft"
        
  - name: Papiersaal
    type: concert
    city: Zurich
    url: "https://www.papiersaal.ch/"
    event: ".single-act"
    fields:
      title:
        selector: ".col-sm-8 h2 a strong"
      url:
        selector: ".col-sm-8 h2 a"
        relative: true
        on_subpage: ["comment"]
      comment:
        selector: ".col-lg-12 p"
        node_index: 2
        max_length: 200
      date:
        day_month_year:
          selector: ".col-sm-8 h3"
          layout: "Monday, 2. Jan 2006"
          regex_extract:
            exp: "[A-Za-z]+,\\s[0-9]{1,2}\\.\\s[\u00e4A-Za-z]{3,4}\\s[0-9]{4}"
        time:
          selector: ".col-sm-8 i"
          layout: "15h04"
          child_index: 3 # we only need this because multiple children match the regex.
          regex_extract:
            exp: "[0-9]{2}h[0-9]{2}"
        location: "Europe/Berlin"
        language: "de_DE"
    paginator:
      selector: ".pull-right"
      relative: true
    filters:
      - field: "title"
        regex_ignore: ".*Abgesagt.*"
      - field: "title"
        regex_ignore: ".*Verschoben.*"
      - field: "title"
        regex_ignore: ".*VERSCHOBEN.*"

  - name: X-TRA
    type: concert
    city: Zurich
    url: "https://www.x-tra.ch/en/agenda/concerts/"
    event: ".events .tile li"
    fields:
      title:
        selector: ".text h2"
      url:
        selector: "a"
        relative: true
        on_subpage: ["date", "comment"]
      comment:
        selector: ".left .content p"
        max_length: 200
      date:
        day_month_year:
          selector: ".caption .text h3"
          layout: "Mon 02.01.06"
        time:
          selector: ".time li strong"
          node_index: 1
          layout: "3.04 p.m. "
        location: "Europe/Berlin"
        language: "en_US"

  - name: Walcheturm
    type: concert
    city: Zurich
    url: "https://walcheturm.ch/agenda/"
    event: "#projectlist a"
    fields:
      title:
        selector: ".content h1"
      url:
        selector: ""
        relative: true
      date:
        day_month_year:
          selector: ".content p"
          regex_extract:
            exp: "([0-9]{2}\\.){2}[0-9]{4}"
            index: 0
          layout: "02.01.2006"
        time:
          selector: ".content p"
          regex_extract:
            exp: "[0-9]{2}:[0-9]{2}"
            index: 0
          layout: "15:04"
