scrapers:
  - name: LifeQuotes
    url: https://www.goodreads.com/quotes/tag/life
    item: ".quote"
    fields:
      dynamic:
        - name: "quote"
          location:
            selector: ".quoteText"
        - name: "author"
          location:
            selector: ".authorOrTitle"