writer:
  type: "api"

scrapers:
  - name: LifeQuotes
    url: https://www.goodreads.com/quotes/tag/life
    item: ".quote"
    fields:
      - name: "quote"
        location:
          selector: ".quoteText"
      - name: "author"
        location:
          selector: ".authorOrTitle"
