name: crawl_events

on:
  schedule:
    - cron: "0 2 * * 0"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  crawl-all-events:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    environment: crawl-env

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Setup Go environment
        uses: actions/setup-go@v2.1.5
        with:
          go-version: 1.17.8
      
      # Runs a single command using the runners shell
      - name: Run the scraper
        run: go run main.go -config concerts-config.yml -store
        env:
          API_USER: ${{ secrets.API_USER }}
          API_PASSWORD: ${{ secrets.API_PASSWORD }}
          EVENT_API: ${{ secrets.EVENT_API }}

